### ISSUE TITLE
Completion block is called from background thread

### ISSUE THREAD

**Issue by alex314** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#26]
Completion block is called not in the main thread if the album didn't exist before the call.

**Comment by Kjuly** [comment]
Hi @alex314 , thx for the feedback, try the latest version v1.3.0, it should works now. ;)

---
**PHPhotoLibrary**'s `-performChanges:completionHandler:` will run asynchronously, this's the reason.

Now if u invoke `-saveImage:toAlbum:completion:failure:` in main thread to save image, it'll follows ur choice to run `-performChangesAndWait:error:` synchronously to create new album if the album not exists; Otherwise, it'll run `-performChanges:completionHandler:` asynchronously like the demo does.
